spring:
  application:
    name: numbers

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_SCHEMA_NAME:numbers}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baselineOnMigrate: true
    locations:
      - db/migration/

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    context-path: ""
  port: ${SERVER_PORT:8088}

wikipedia:
  url: ${WIKI_URL:https://en.wikipedia.org/wiki/List_of_country_calling_codes#Alphabetical_order}

#logging:
#  level:
#    root: DEBUG
